---
name: build-check
on:
  - push
  - pull_request
jobs:
  build-check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - '1.15'
          - '1.14'
          - '1.13'
          - '1.13'
          - '1.12'
          - '1.11'
    name: build-check Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make build_check
